// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Ring from "./Ring.res.mjs";
import * as Music from "./Music.res.mjs";
import * as React from "react";
import * as Fretboard from "./Fretboard.res.mjs";
import * as ScaleCircle from "./ScaleCircle.res.mjs";
import * as ButtonToggle from "./ButtonToggle.res.mjs";
import * as Primitive_object from "@rescript/runtime/lib/es6/Primitive_object.js";
import * as JsxRuntime from "react/jsx-runtime";

function App(props) {
  let note = props.note;
  let scale = props.scale;
  let root = props.root;
  let match = React.useState(() => root);
  let setRootNote = match[1];
  let rootNote = match[0];
  let match$1 = React.useState(() => scale);
  let setScalePattern = match$1[1];
  let scalePattern = match$1[0];
  let majorScale = Music.Scale.make(scalePattern, rootNote);
  let unusedNotes = Ring.subtract(Music.chromaticRing, majorScale.notes);
  let match$2 = React.useState(() => note);
  let setActiveNote = match$2[1];
  let activeNote = match$2[0];
  React.useEffect(() => {
    let params = new URLSearchParams(location.search);
    params.set("root", Music.urlEncodeNote(rootNote));
    params.set("scale", Music.urlEncodeScalePattern(scalePattern));
    if (activeNote !== undefined) {
      params.set("note", Music.urlEncodeNote(activeNote));
    } else {
      params.delete("note");
    }
    let newUrl = location.origin + location.pathname + `?` + params.toString();
    history.replaceState({}, "", newUrl);
  }, [
    rootNote,
    scalePattern,
    activeNote
  ]);
  let tmp;
  if (activeNote !== undefined) {
    let chord = Music.Scale.chordForNote(majorScale, activeNote);
    let grayedOut = Music.allNotes.difference(new Set([
      chord.root,
      chord.third,
      chord.fifth
    ]));
    tmp = JsxRuntime.jsxs(JsxRuntime.Fragment, {
      children: [
        JsxRuntime.jsx("h2", {
          children: Music.chordName(chord),
          className: "text-3xl font-bold"
        }),
        JsxRuntime.jsx(Fretboard.make, {
          openStrings: [
            "E",
            "B",
            "G",
            "D",
            "A",
            "E"
          ],
          className: "my-6 mx-auto",
          grayedOut: grayedOut,
          primary: activeNote,
          secondary: new Set([
            chord.third,
            chord.fifth
          ])
        })
      ]
    });
  } else {
    tmp = null;
  }
  return JsxRuntime.jsxs("div", {
    children: [
      JsxRuntime.jsx("h1", {
        children: "Intervallo",
        className: "font-title text-2xl md:text-3xl lg:text-4xl font-bold"
      }),
      JsxRuntime.jsx(ButtonToggle.make, {
        items: Music.chromaticRing.items,
        onClick: note => {
          setRootNote(param => note);
          setActiveNote(param => {});
        },
        activeItem: rootNote,
        renderItem: Music.noteElement,
        keyOf: note => note
      }),
      JsxRuntime.jsx(ButtonToggle.make, {
        items: [
          "Major",
          "Minor"
        ],
        onClick: pattern => {
          setScalePattern(param => {
            if (pattern === "Major") {
              return Music.majorScalePattern;
            } else {
              return Music.minorScalePattern;
            }
          });
          setActiveNote(param => {});
        },
        activeItem: Primitive_object.equal(scalePattern, Music.majorScalePattern) ? "Major" : "Minor",
        renderItem: prim => prim,
        keyOf: id => id
      }),
      JsxRuntime.jsx("h2", {
        children: "Scale",
        className: "text-3xl font-bold"
      }),
      JsxRuntime.jsx(Fretboard.make, {
        openStrings: [
          "E",
          "B",
          "G",
          "D",
          "A",
          "E"
        ],
        className: "my-6 mx-auto",
        grayedOut: unusedNotes,
        primary: majorScale.rootNote
      }),
      JsxRuntime.jsxs("div", {
        children: [
          JsxRuntime.jsx(ScaleCircle.make, {
            scale: majorScale,
            radius: 300,
            onNoteClick: note => setActiveNote(param => note),
            activeNote: activeNote
          }),
          activeNote !== undefined ? JsxRuntime.jsx("button", {
              children: "reset",
              className: "btn btn-outline",
              onClick: param => setActiveNote(param => {})
            }) : null
        ],
        className: "flex flex-col items-center justify-center gap-4"
      }),
      tmp
    ],
    className: "w-full h-full p-8"
  });
}

let make = App;

export {
  make,
}
/* Music Not a pure module */
