// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Music from "./Music.res.mjs";
import * as React from "react";
import * as ScaleCircle from "./ScaleCircle.res.mjs";
import * as JsxRuntime from "react/jsx-runtime";

let cMajor = Music.Scale.make(Music.majorScalePattern, "D");

let cMajorChord = Music.Scale.chordForNote(cMajor, "A");

function App(props) {
  let match = React.useState(() => "C");
  let setRootNote = match[1];
  let rootNote = match[0];
  let majorScale = Music.Scale.make(Music.majorScalePattern, rootNote);
  return JsxRuntime.jsxs("div", {
    children: [
      JsxRuntime.jsx("h1", {
        children: "Intervallo",
        className: "font-title text-2xl md:text-3xl lg:text-4xl font-bold"
      }),
      JsxRuntime.jsx("div", {
        children: Music.chromaticRing.items.map((note, idx) => {
          let className = [
            note === rootNote ? "btn-neutral" : "btn-outline",
            idx > 0 ? "border-l-[0]" : "",
            idx === 0 ? "rounded-l-md" : "",
            idx === (Music.chromaticRing.items.length - 1 | 0) ? "rounded-r-md" : ""
          ].join(" ");
          return JsxRuntime.jsx("button", {
            children: Music.displayNote(note),
            className: `btn rounded-none ` + className,
            onClick: param => setRootNote(param => note)
          }, note);
        }),
        className: "flex flex-row justify-center py-4"
      }),
      JsxRuntime.jsx(ScaleCircle.make, {
        scale: majorScale,
        radius: 300
      }),
      JsxRuntime.jsx("code", {
        children: JSON.stringify(majorScale),
        className: "mt-4 block"
      }),
      JsxRuntime.jsx("code", {
        children: JSON.stringify(cMajorChord),
        className: "mt-4 block"
      })
    ],
    className: "w-full h-full p-8"
  });
}

let make = App;

export {
  make,
}
/* cMajor Not a pure module */
