// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Primitive_object from "@rescript/runtime/lib/es6/Primitive_object.js";
import * as JsxRuntime from "react/jsx-runtime";

function ButtonToggle(props) {
  let keyOf = props.keyOf;
  let renderItem = props.renderItem;
  let activeItem = props.activeItem;
  let onClick = props.onClick;
  let items = props.items;
  let itemCount = items.length;
  return JsxRuntime.jsx("div", {
    children: items.map((item, idx) => {
      let className = [
        Primitive_object.equal(item, activeItem) ? "btn-neutral" : "btn-outline",
        idx > 0 ? "border-l-[0]" : "",
        idx === 0 ? "rounded-l-md" : "",
        idx === (itemCount - 1 | 0) ? "rounded-r-md" : ""
      ].join(" ");
      return JsxRuntime.jsx("button", {
        children: renderItem(item),
        className: `btn rounded-none ` + className,
        onClick: param => onClick(item)
      }, keyOf(item));
    }),
    className: "flex flex-row justify-center py-4"
  });
}

let make = ButtonToggle;

export {
  make,
}
/* react/jsx-runtime Not a pure module */
