// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Music from "./Music.res.mjs";
import * as JsxRuntime from "react/jsx-runtime";

function ChordsInScale(props) {
  let scale = props.scale;
  return JsxRuntime.jsx("ul", {
    children: scale.notes.items.map(note => JsxRuntime.jsx("li", {
      children: Music.chordName(Music.Scale.chordForNote(scale, note)),
      className: "text-lg py-1 text-zinc-600"
    }, Music.displayNote(note)))
  });
}

let make = ChordsInScale;

export {
  make,
}
/* Music Not a pure module */
