// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Ring from "./Ring.res.mjs";
import * as Music from "./Music.res.mjs";
import * as Stdlib_Array from "@rescript/runtime/lib/es6/Stdlib_Array.js";
import * as JsxRuntime from "react/jsx-runtime";

function Fretboard$Note(props) {
  let __highlight = props.highlight;
  let highlight = __highlight !== undefined ? __highlight : false;
  let colors = highlight ? "bg-sky-800 text-white" : "bg-zinc-950 text-white";
  return JsxRuntime.jsx("div", {
    children: Music.noteElement(props.note),
    className: `rounded-full ` + colors + ` flex items-center justify-center h-[30px] w-[30px] text-sm`
  });
}

let Note = {
  make: Fretboard$Note
};

function Fretboard$Fret(props) {
  let note = props.note;
  return JsxRuntime.jsx("div", {
    children: JsxRuntime.jsx(Fretboard$Note, {
      note: note,
      highlight: note === "FSharp"
    }),
    className: "border-r-4 border-neutral-400 flex-1 min-w-[40px] p-2 flex items-center justify-end"
  });
}

let Fret = {
  make: Fretboard$Fret
};

function Fretboard$OpenString(props) {
  return JsxRuntime.jsx("div", {
    children: JsxRuntime.jsx(Fretboard$Note, {
      note: props.openNote
    }),
    className: "shrink-0"
  });
}

let OpenString = {
  make: Fretboard$OpenString
};

function Fretboard$GuitarString(props) {
  let __maxFrets = props.maxFrets;
  let openNote = props.openNote;
  let maxFrets = __maxFrets !== undefined ? __maxFrets : 15;
  let openNoteIdx = Ring.indexOf(Music.chromaticRing, openNote);
  return JsxRuntime.jsxs("div", {
    children: [
      JsxRuntime.jsx(Fretboard$OpenString, {
        openNote: openNote
      }),
      JsxRuntime.jsx("div", {
        children: Stdlib_Array.fromInitializer(maxFrets, i => {
          let fret = i + 1 | 0;
          let note = Ring.at(Music.chromaticRing, openNoteIdx + fret | 0);
          return JsxRuntime.jsx(Fretboard$Fret, {
            note: note
          }, String(i));
        }),
        className: "border border-zinc-950 flex flex-1"
      })
    ],
    className: "flex gap-4 items-center w-full"
  });
}

let GuitarString = {
  make: Fretboard$GuitarString
};

function Fretboard$FretMarker(props) {
  let fret = props.fret;
  let positionInOctave = fret % 12;
  let hasSingleDot = [
    3,
    5,
    7,
    9
  ].includes(positionInOctave);
  let hasDoubleDot = fret % 12 === 0;
  return JsxRuntime.jsx("div", {
    children: hasDoubleDot ? JsxRuntime.jsxs("div", {
        children: [
          JsxRuntime.jsx("div", {
            className: "bg-amber-100 w-[20px] h-[20px] rounded-full"
          }),
          JsxRuntime.jsx("div", {
            className: "bg-amber-100 w-[20px] h-[20px] rounded-full"
          })
        ],
        className: "h-1/2 flex flex-col justify-evenly items-center"
      }) : (
        hasSingleDot ? JsxRuntime.jsx("div", {
            className: "bg-amber-100 w-[20px] h-[20px] rounded-full"
          }) : null
      ),
    className: "flex-1 min-w-[40px] h-full flex flex-col items-center justify-center"
  });
}

let FretMarker = {
  make: Fretboard$FretMarker
};

function Fretboard$FretMarkers(props) {
  return JsxRuntime.jsxs("div", {
    children: [
      JsxRuntime.jsx("div", {
        className: "shrink-0 w-[30px]"
      }),
      JsxRuntime.jsx("div", {
        children: Stdlib_Array.fromInitializer(props.maxFrets, i => JsxRuntime.jsx(Fretboard$FretMarker, {
          fret: i + 1 | 0
        }, i.toString())),
        className: "flex flex-1 h-full"
      })
    ],
    className: "absolute inset-0 flex gap-4 z-[-1] pointer-events-none"
  });
}

let FretMarkers = {
  make: Fretboard$FretMarkers
};

function Fretboard(props) {
  let __className = props.className;
  let __maxFrets = props.maxFrets;
  let maxFrets = __maxFrets !== undefined ? __maxFrets : 15;
  let className = __className !== undefined ? __className : "";
  return JsxRuntime.jsxs("div", {
    children: [
      JsxRuntime.jsx(Fretboard$FretMarkers, {
        maxFrets: maxFrets
      }),
      props.openStrings.map(openNote => JsxRuntime.jsx(Fretboard$GuitarString, {
        openNote: openNote,
        maxFrets: maxFrets
      }, Music.displayNote(openNote)))
    ],
    className: `overflow-auto select-none relative isolate ` + className
  });
}

let make = Fretboard;

export {
  Note,
  Fret,
  OpenString,
  GuitarString,
  FretMarker,
  FretMarkers,
  make,
}
/* Music Not a pure module */
