// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Ring from "./Ring.res.mjs";
import * as Music from "./Music.res.mjs";
import * as Stdlib_Array from "@rescript/runtime/lib/es6/Stdlib_Array.js";
import * as JsxRuntime from "react/jsx-runtime";

function Fretboard$Note(props) {
  let colors;
  switch (props.highlight) {
    case "PrimaryNote" :
      colors = "bg-yellow-400 text-white";
      break;
    case "SecondaryNote" :
      colors = "bg-sky-500 text-white";
      break;
    case "GrayedOutNote" :
      colors = "bg-zinc-950 opacity-10 text-white";
      break;
    case "RegularNote" :
      colors = "bg-zinc-950 text-white";
      break;
  }
  return JsxRuntime.jsx("div", {
    children: Music.noteElement(props.note),
    className: `z-[2] rounded-full ` + colors + ` flex items-center justify-center h-[30px] w-[30px] text-sm`
  });
}

let Note = {
  make: Fretboard$Note
};

function Fretboard$Fret(props) {
  return JsxRuntime.jsx("div", {
    children: JsxRuntime.jsx(Fretboard$Note, {
      note: props.note,
      highlight: props.highlight
    }),
    className: "bg-yellow-800 border-r-4 border-neutral-400 flex-1 min-w-[40px] p-2 flex items-center justify-end"
  });
}

let Fret = {
  make: Fretboard$Fret
};

function Fretboard$OpenString(props) {
  return JsxRuntime.jsx("div", {
    children: JsxRuntime.jsx(Fretboard$Note, {
      note: props.openNote,
      highlight: props.highlight
    }),
    className: "shrink-0"
  });
}

let OpenString = {
  make: Fretboard$OpenString
};

function Fretboard$GuitarString(props) {
  let highlighter = props.highlighter;
  let __maxFrets = props.maxFrets;
  let openNote = props.openNote;
  let maxFrets = __maxFrets !== undefined ? __maxFrets : 15;
  let openNoteIdx = Ring.indexOf(Music.chromaticRing, openNote);
  return JsxRuntime.jsxs("div", {
    children: [
      JsxRuntime.jsx(Fretboard$OpenString, {
        openNote: openNote,
        highlight: highlighter(openNote)
      }),
      JsxRuntime.jsx("div", {
        children: Stdlib_Array.fromInitializer(maxFrets, i => {
          let fret = i + 1 | 0;
          let note = Ring.at(Music.chromaticRing, openNoteIdx + fret | 0);
          return JsxRuntime.jsx(Fretboard$Fret, {
            note: note,
            highlight: highlighter(note)
          }, String(i));
        }),
        className: "border border-zinc-950 flex flex-1"
      })
    ],
    className: "flex gap-4 items-center w-full"
  });
}

let GuitarString = {
  make: Fretboard$GuitarString
};

function Fretboard$FretMarker(props) {
  let fret = props.fret;
  let positionInOctave = fret % 12;
  let hasSingleDot = [
    3,
    5,
    7,
    9
  ].includes(positionInOctave);
  let hasDoubleDot = fret % 12 === 0;
  return JsxRuntime.jsx("div", {
    children: hasDoubleDot ? JsxRuntime.jsxs("div", {
        children: [
          JsxRuntime.jsx("div", {
            className: "bg-amber-100 w-[20px] h-[20px] rounded-full"
          }),
          JsxRuntime.jsx("div", {
            className: "bg-amber-100 w-[20px] h-[20px] rounded-full"
          })
        ],
        className: "h-1/2 flex flex-col justify-evenly items-center"
      }) : (
        hasSingleDot ? JsxRuntime.jsx("div", {
            className: "bg-amber-100 w-[20px] h-[20px] rounded-full"
          }) : null
      ),
    className: "flex-1 min-w-[40px] h-full flex flex-col items-center justify-center"
  });
}

let FretMarker = {
  make: Fretboard$FretMarker
};

function Fretboard$FretMarkers(props) {
  return JsxRuntime.jsxs("div", {
    children: [
      JsxRuntime.jsx("div", {
        className: "shrink-0 w-[30px]"
      }),
      JsxRuntime.jsx("div", {
        children: Stdlib_Array.fromInitializer(props.maxFrets, i => JsxRuntime.jsx(Fretboard$FretMarker, {
          fret: i + 1 | 0
        }, i.toString())),
        className: "flex flex-1 h-full"
      })
    ],
    className: "absolute z-[1] inset-0 flex gap-4 pointer-events-none"
  });
}

let FretMarkers = {
  make: Fretboard$FretMarkers
};

function Fretboard(props) {
  let __secondary = props.secondary;
  let primary = props.primary;
  let __grayedOut = props.grayedOut;
  let __className = props.className;
  let __maxFrets = props.maxFrets;
  let maxFrets = __maxFrets !== undefined ? __maxFrets : 15;
  let className = __className !== undefined ? __className : "";
  let grayedOut = __grayedOut !== undefined ? __grayedOut : new Set();
  let secondary = __secondary !== undefined ? __secondary : new Set();
  let highlighter = note => {
    if (primary !== undefined && note === primary) {
      return "PrimaryNote";
    }
    if (secondary.has(note)) {
      return "SecondaryNote";
    } else if (grayedOut.has(note)) {
      return "GrayedOutNote";
    } else {
      return "RegularNote";
    }
  };
  return JsxRuntime.jsxs("div", {
    children: [
      JsxRuntime.jsx(Fretboard$FretMarkers, {
        maxFrets: maxFrets
      }),
      props.openStrings.map(openNote => JsxRuntime.jsx(Fretboard$GuitarString, {
        openNote: openNote,
        maxFrets: maxFrets,
        highlighter: highlighter
      }, Music.displayNote(openNote)))
    ],
    className: `overflow-auto select-none relative ` + className
  });
}

let make = Fretboard;

export {
  Note,
  Fret,
  OpenString,
  GuitarString,
  FretMarker,
  FretMarkers,
  make,
}
/* Music Not a pure module */
