// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Ring from "./Ring.res.mjs";
import * as Music from "./Music.res.mjs";
import * as Iluvatar from "./Iluvatar.res.mjs";
import * as Stdlib_Array from "@rescript/runtime/lib/es6/Stdlib_Array.js";
import * as JsxRuntime from "react/jsx-runtime";

function Fretboard$Note(props) {
  let __highlight = props.highlight;
  let highlight = __highlight !== undefined ? __highlight : false;
  let colors = highlight ? "bg-sky-800 text-white" : "bg-zinc-950 text-white";
  return JsxRuntime.jsx("div", {
    children: Music.noteElement(props.note),
    className: `rounded-full ` + colors + ` flex items-center justify-center h-[30px] w-[30px] text-sm`
  });
}

let Note = {
  make: Fretboard$Note
};

function Fretboard$Fret(props) {
  let note = props.note;
  return JsxRuntime.jsx("div", {
    children: JsxRuntime.jsx(Fretboard$Note, {
      note: note,
      highlight: note === "FSharp"
    }),
    className: "border-r-4 border-neutral-400 w-[100px] p-2 flex items-center justify-end"
  });
}

let Fret = {
  make: Fretboard$Fret
};

function Fretboard$OpenString(props) {
  return JsxRuntime.jsx(Fretboard$Note, {
    note: props.openNote
  });
}

let OpenString = {
  make: Fretboard$OpenString
};

function Fretboard$GuitarString(props) {
  let __maxFrets = props.maxFrets;
  let openNote = props.openNote;
  let maxFrets = __maxFrets !== undefined ? __maxFrets : 15;
  let openNoteIdx = Ring.indexOf(Music.chromaticRing, openNote);
  return JsxRuntime.jsxs("div", {
    children: [
      JsxRuntime.jsx(Fretboard$OpenString, {
        openNote: openNote
      }),
      JsxRuntime.jsx("div", {
        children: Stdlib_Array.fromInitializer(maxFrets, i => {
          let fret = i + 1 | 0;
          let note = Ring.at(Music.chromaticRing, openNoteIdx + fret | 0);
          return JsxRuntime.jsx(Fretboard$Fret, {
            note: note
          }, String(i));
        }),
        className: "border border-zinc-950 flex"
      })
    ],
    className: "flex gap-4 items-center"
  });
}

let GuitarString = {
  make: Fretboard$GuitarString
};

function Fretboard$FretMarkers(props) {
  return Stdlib_Array.fromInitializer(props.maxFrets, i => {
    let fret = i + 1 | 0;
    let marker;
    if (fret % 12 === 0) {
      marker = "DoubleDot";
    } else {
      let positionInOctave = fret % 12;
      marker = [
        3,
        5,
        7,
        9
      ].includes(positionInOctave) ? "SingleDot" : "NoDots";
    }
    let left = Iluvatar.px((48 + (i * 100 | 0) | 0) + 50 | 0);
    switch (marker) {
      case "SingleDot" :
        return JsxRuntime.jsx("div", {
          className: "absolute top-1/2 z-[-1] -translate-y-1/2 -translate-x-1/2 bg-amber-100 w-[25px] h-[25px] rounded-full",
          style: {
            left: left
          }
        }, i.toString());
      case "DoubleDot" :
        return JsxRuntime.jsxs(JsxRuntime.Fragment, {
          children: [
            JsxRuntime.jsx("div", {
              className: "absolute top-1/3 z-[-1] -translate-y-1/2 -translate-x-1/2 bg-amber-100 w-[25px] h-[25px] rounded-full",
              style: {
                left: left
              }
            }, i.toString()),
            JsxRuntime.jsx("div", {
              className: "absolute top-2/3 z-[-1] -translate-y-1/2 -translate-x-1/2 bg-amber-100 w-[25px] h-[25px] rounded-full",
              style: {
                left: left
              }
            }, i.toString())
          ]
        });
      case "NoDots" :
        return null;
    }
  });
}

let FretMarkers = {
  make: Fretboard$FretMarkers
};

function Fretboard(props) {
  let __className = props.className;
  let __maxFrets = props.maxFrets;
  let maxFrets = __maxFrets !== undefined ? __maxFrets : 15;
  let className = __className !== undefined ? __className : "";
  return JsxRuntime.jsxs("div", {
    children: [
      JsxRuntime.jsx(Fretboard$FretMarkers, {
        maxFrets: maxFrets
      }),
      props.openStrings.map(openNote => JsxRuntime.jsx(Fretboard$GuitarString, {
        openNote: openNote,
        maxFrets: maxFrets
      }, Music.displayNote(openNote)))
    ],
    className: `overflow-auto select-none relative isolate bg-transparent ` + className
  });
}

let make = Fretboard;

export {
  Note,
  Fret,
  OpenString,
  GuitarString,
  FretMarkers,
  make,
}
/* Music Not a pure module */
