// Generated by ReScript, PLEASE EDIT WITH CARE

import * as App from "./App.res.mjs";
import * as Music from "./Music.res.mjs";
import * as React from "react";
import * as Client from "react-dom/client";
import * as JsxRuntime from "react/jsx-runtime";

import './index.css'
;

let domElement = document.querySelector("#root");

if (!(domElement == null)) {
  let params = new URLSearchParams(location.search);
  let root = params.get("root");
  let root$1;
  root$1 = root === null ? "C" : Music.urlDecodeNote(root);
  let scale = params.get("scale");
  let scale$1;
  scale$1 = scale === null ? Music.majorScalePattern : Music.urlDecodeScalePattern(scale);
  let note = params.get("note");
  let note$1;
  note$1 = note === null ? undefined : Music.urlDecodeNote(note);
  Client.createRoot(domElement).render(JsxRuntime.jsx(React.StrictMode, {
    children: JsxRuntime.jsx(App.make, {
      root: root$1,
      scale: scale$1,
      note: note$1
    })
  }));
}

/*  Not a pure module */
