// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Primitive_int from "@rescript/runtime/lib/es6/Primitive_int.js";
import * as Primitive_object from "@rescript/runtime/lib/es6/Primitive_object.js";

function make(source) {
  return {
    items: source
  };
}

function length(ring) {
  return ring.items.length;
}

function at(ring, index) {
  let len = ring.items.length;
  let normalizedIdx = Primitive_int.mod_(index, len);
  let finalIdx = normalizedIdx < 0 ? normalizedIdx + len | 0 : normalizedIdx;
  return ring.items[finalIdx];
}

function contains(ring, node) {
  return ring.items.some(item => Primitive_object.equal(item, node));
}

function indexOf(ring, node) {
  return ring.items.indexOf(node);
}

function distanceBetween(ring, from, to) {
  let fromIdx = indexOf(ring, from);
  let toIdx = indexOf(ring, to);
  let len = ring.items.length;
  if (toIdx >= fromIdx) {
    return toIdx - fromIdx | 0;
  } else {
    return (len - fromIdx | 0) + toIdx | 0;
  }
}

export {
  make,
  length,
  at,
  contains,
  indexOf,
  distanceBetween,
}
/* No side effect */
