// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Music from "./Music.res.mjs";
import * as JsxRuntime from "react/jsx-runtime";

function ScaleCircle(props) {
  let __className = props.className;
  let __padding = props.padding;
  let __radius = props.radius;
  let scale = props.scale;
  let radius = __radius !== undefined ? __radius : 300;
  let padding = __padding !== undefined ? __padding : 20;
  let className = __className !== undefined ? __className : "";
  let size = radius + (padding << 1) | 0;
  let center = size / 2;
  let orbitRadius = radius / 2;
  let rootNote = scale.rootNote;
  return JsxRuntime.jsx("div", {
    children: scale.notes.items.map((note, idx) => {
      let semitones = Music.semitonesBetween(rootNote, note);
      let degrees = semitones * 30;
      let angleInRadians = (degrees - 90) * Math.PI / 180;
      let x = orbitRadius * Math.cos(angleInRadians) + center;
      let y = orbitRadius * Math.sin(angleInRadians) + center;
      return JsxRuntime.jsx("div", {
        children: Music.displayNote(note),
        className: "absolute -translate-x-1/2 -translate-y-1/2",
        style: {
          left: String(x) + "px",
          top: String(y) + "px"
        }
      }, String(idx));
    }),
    className: `relative border ` + className,
    style: {
      height: String(size) + "px",
      width: String(size) + "px"
    }
  });
}

let make = ScaleCircle;

export {
  make,
}
/* Music Not a pure module */
