// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Music from "./Music.res.mjs";
import * as Iluvatar from "./Iluvatar.res.mjs";
import * as Primitive_int from "@rescript/runtime/lib/es6/Primitive_int.js";
import * as JsxRuntime from "react/jsx-runtime";

function describeArc(centerX, centerY, radius, startAngle, endAngle) {
  let startRad = startAngle * Math.PI / 180;
  let endRad = endAngle * Math.PI / 180;
  let startX = centerX + radius * Math.cos(startRad);
  let startY = centerY + radius * Math.sin(startRad);
  let endX = centerX + radius * Math.cos(endRad);
  let endY = centerY + radius * Math.sin(endRad);
  let angleDiff = endAngle - startAngle;
  let largeArcFlag = angleDiff > 180 ? "1" : "0";
  return `M ` + startX.toString() + ` ` + startY.toString() + ` A ` + radius.toString() + ` ` + radius.toString() + ` 0 ` + largeArcFlag + ` 1 ` + endX.toString() + ` ` + endY.toString();
}

function strokeColorForSemitones(semitones) {
  switch (semitones) {
    case 1 :
      return "stroke-neutral-300";
    case 2 :
      return "stroke-neutral-600";
    case 3 :
      return "stroke-red-500";
    default:
      return "stroke-base-content";
  }
}

function ScaleCircle(props) {
  let __className = props.className;
  let __padding = props.padding;
  let __radius = props.radius;
  let scale = props.scale;
  let radius = __radius !== undefined ? __radius : 300;
  let padding = __padding !== undefined ? __padding : 20;
  let className = __className !== undefined ? __className : "";
  let size = radius + (padding << 1) | 0;
  let center = size / 2;
  let orbitRadius = radius / 2;
  let rootNote = scale.rootNote;
  let notes = scale.notes.items;
  let noteAngles = notes.map(note => {
    let semitones = Music.semitonesBetween(rootNote, note);
    return semitones * 30 - 90;
  });
  let arcs = notes.map((note, idx) => {
    let nextIdx = Primitive_int.mod_(idx + 1 | 0, notes.length);
    let nextNote = notes[nextIdx];
    let startAngle = noteAngles[idx];
    let endAngle = noteAngles[nextIdx];
    let endAngle$1 = endAngle <= startAngle ? endAngle + 360 : endAngle;
    let semitones = Music.semitonesBetween(note, nextNote);
    let strokeColor = strokeColorForSemitones(semitones);
    let arcPath = describeArc(center, center, orbitRadius, startAngle + 6, endAngle$1 - 6);
    return JsxRuntime.jsx("path", {
      className: strokeColor + ` fill-none stroke-3`,
      d: arcPath
    }, `arc-` + String(idx));
  });
  return JsxRuntime.jsxs("div", {
    children: [
      JsxRuntime.jsx("svg", {
        children: arcs,
        className: "absolute inset-0 pointer-events-none",
        height: String(size),
        width: String(size)
      }),
      notes.map((note, idx) => {
        let semitones = Music.semitonesBetween(rootNote, note);
        let degrees = semitones * 30;
        let angleInRadians = (degrees - 90) * Math.PI / 180;
        let x = orbitRadius * Math.cos(angleInRadians) + center;
        let y = orbitRadius * Math.sin(angleInRadians) + center;
        return JsxRuntime.jsx("div", {
          children: Music.noteElement(note),
          className: "absolute -translate-x-1/2 -translate-y-1/2 cursor-pointer",
          style: {
            left: Iluvatar.pxf(x),
            top: Iluvatar.pxf(y)
          }
        }, String(idx));
      })
    ],
    className: `relative mx-auto ` + className,
    style: {
      height: Iluvatar.px(size),
      width: Iluvatar.px(size)
    }
  });
}

let make = ScaleCircle;

export {
  make,
}
/* Music Not a pure module */
